local M = {}

M.BOARD_COLUMNS = 40
M.BOARD_ROWS = 22

M.TILE_HERO = 5
M.TILE_GRASS = 70

M.SCENE_TILEMAP_URL = "/scene#scene"

M.LAYER_TERRAIN = "terrain"
M.LAYER_CHARACTER = "character"

M.ACTION_UP = "UP"
M.ACTION_DOWN = "DOWN"
M.ACTION_LEFT = "LEFT"
M.ACTION_RIGHT = "RIGHT"
M.ACTION_GREEN = "GREEN"
M.ACTION_RED = "RED"

return M