local M = {}

M.BOARD_COLUMNS = 40
M.BOARD_ROWS = 22

M.TEXT_COLUMNS = 40
M.TEXT_ROWS = 22

M.TILE_HERO = 5
M.TILE_BLANK = 18
M.TILE_PINE = 85

M.SCENE_TILEMAP_URL = "/scene#scene"
M.MESSAGE_TILEMAP_URL = "/message#message"
M.MESSAGE_URL = "/message"

M.LAYER_TERRAIN = "terrain"
M.LAYER_CHARACTER = "character"
M.LAYER_TEXT = "text"

M.ACTION_UP = "UP"
M.ACTION_DOWN = "DOWN"
M.ACTION_LEFT = "LEFT"
M.ACTION_RIGHT = "RIGHT"
M.ACTION_GREEN = "GREEN"
M.ACTION_RED = "RED"

M.MSG_ADD_MESSAGE = "ADD_MESSAGE"

return M